name: dart_vader_cli
description: A for fun project to make use of my studies of making executable dart packages.
version: 1.0.1
repository: https://github.com/LuizJarduli/dart-vader
homepage: https://github.com/LuizJarduli/dart-vader
issue_tracker: https://github.com/LuizJarduli/dart-vader/issues
documentation: https://github.com/LuizJarduli/dart-vader/blob/main/README.md
topics: 
  - cli
  - audio
  - dart
  - vader
  - dark-side

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  enough_ascii_art: ^1.1.0
  mason_logger: ^0.3.3
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.15
  build_version: ^2.1.1
  husky: ^0.1.7
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0

executables: 
  dart_vader_cli:

platforms:
  linux:
  macos:
  windows:

